name: meshalate
version: 0.0.1
author: Blake Courter <bcourter@gmail.com>
homepage: http://threedart.github.com/meshalate
dependencies:
  browser: '>=0.9.0 <0.10.0'
  three: any
  vector_math: any
dev_dependencies:
  hop: '>=0.27.0 <0.28.0'
  unittest: any
